# Start with a base image containing Java runtime
FROM openjdk:8

# Add Maintainer Info
MAINTAINER priyanshNigam <lucklypriyansh@gmail.com>

# Add a volume pointing to /tmp
VOLUME /tmp

# Make port 8080 available to the world outside this container
EXPOSE 8080

# Add the application's jar to the container
ADD target/hrportal.jar hrportal.jar

# Run the jar file 
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","hrportal.jar"]

